#!/bin/bash
# Browser HSTS cache tozalash uchun ko'rsatma

echo "=================================="
echo "BROWSER HSTS MUAMMOSINI HAL QILISH"
echo "=================================="
echo ""
echo "Muammo: Browser avtomatik HTTPS ga o'tkazmoqda"
echo "Yechim: HSTS cache ni tozalash"
echo ""
echo "--- CHROME/CHROMIUM ---"
echo "1. Brauzer addressga kiriting:"
echo "   chrome://net-internals/#hsts"
echo ""
echo "2. Pastdagi 'Delete domain security policies' bo'limida:"
echo "   - 'localhost' ni kiriting va 'Delete' bosing"
echo "   - '127.0.0.1' ni kiriting va 'Delete' bosing"
echo ""
echo "3. Browserni yoping va qayta oching"
echo "4. http://127.0.0.1:8000 ga kiring (http:// bo'lsin!)"
echo ""
echo "--- FIREFOX ---"
echo "1. Settings → Privacy & Security"
echo "2. 'Clear Data' tugmasini bosing"
echo "3. 'Cookies and Site Data' ni tozalang"
echo "4. Browserni yoping va qayta oching"
echo "5. http://127.0.0.1:8000 ga kiring"
echo ""
echo "--- ENG OSON YO'L ---"
echo "Incognito/Private mode ishlatish:"
echo "- Chrome: Ctrl+Shift+N"
echo "- Firefox: Ctrl+Shift+P"
echo ""
echo "So'ng: http://127.0.0.1:8000 ga kiring"
echo ""
echo "=================================="
