# Generated by Django 5.1.5 on 2026-02-02 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPBlocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(choices=[('ddos', 'DDoS hujum'), ('brute_force', 'Brute force hujum'), ('spam', 'Spam'), ('manual', "Qo'lda bloklangan"), ('suspicious', 'Shubhali faollik')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('is_permanent', models.BooleanField(default=False)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'IP Bloklash',
                'verbose_name_plural': 'IP Bloklashlar',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Tizimga kirish'), ('logout', 'Tizimdan chiqish'), ('registration', 'Registratsiya'), ('failed_login', 'Muvaffaqiyatsiz kirish'), ('password_change', "Parol o'zgartirish"), ('profile_update', 'Profil yangilash')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='core_userac_timesta_646400_idx'), models.Index(fields=['ip_address'], name='core_userac_ip_addr_3e86f6_idx'), models.Index(fields=['user', '-timestamp'], name='core_userac_user_id_c382a9_idx')],
            },
        ),
    ]
