# Generated by Django 5.1.5 on 2026-03-04 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ipblocklist_useractivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBotAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('none', 'Bloklanmagan'), ('temporary', 'Vaqtinchalik bloklangan'), ('permanent', 'Doimiy bloklangan')], default='none', max_length=20)),
                ('blocked_until', models.DateTimeField(blank=True, help_text='Vaqtinchalik blok uchun', null=True)),
                ('block_reason', models.TextField(blank=True, default='', help_text='Bloklash sababi')),
                ('violation_count', models.IntegerField(default=0, help_text='Umumiy qoidabuzarlik soni')),
                ('last_violation_at', models.DateTimeField(blank=True, null=True)),
                ('email_notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_by', models.ForeignKey(blank=True, help_text='Bloklagan admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_blocks_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ChatBot Huquqi',
                'verbose_name_plural': 'ChatBot Huquqlari',
            },
        ),
        migrations.CreateModel(
            name='ChatViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(help_text="So'rov yuborgan foydalanuvchi emaili", max_length=254)),
                ('user_message', models.TextField(help_text='Foydalanuvchi yuborgan xabar')),
                ('ai_response', models.TextField(blank=True, default='', help_text='AI bergan javob')),
                ('violation_type', models.CharField(choices=[('harmful', "Zararli kontent so'rovi"), ('violence', "Zo'ravonlik"), ('adult', 'Kattalar uchun kontent'), ('hacking', 'Hacking/Exploit'), ('spam', 'Spam'), ('off_topic', 'Mavzuga mos emas'), ('harassment', 'Haqorat/Diskriminatsiya'), ('other', 'Boshqa')], default='other', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('critical', 'Kritik')], default='medium', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(default=False, help_text="Admin ko'rib chiqdimi?")),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Admin eslatmalari')),
                ('action_taken', models.CharField(blank=True, default='', help_text="Qanday chora ko'rildi (bloklash, ogohlantirish va h.k.)", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Qoidabuzarlik',
                'verbose_name_plural': 'Chat Qoidabuzarliklar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_chatvi_created_d921a8_idx'), models.Index(fields=['user'], name='core_chatvi_user_id_9d8bc1_idx'), models.Index(fields=['is_reviewed'], name='core_chatvi_is_revi_d96b9f_idx'), models.Index(fields=['violation_type'], name='core_chatvi_violati_69f507_idx')],
            },
        ),
    ]
