# Generated by Django 5.1.5 on 2026-03-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Ruxsat berilgan IP manzili (masalan: 127.0.0.1)', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Ushbu IP manziliga kirish ruxsat etilganmi?')),
                ('description', models.CharField(blank=True, help_text='Qurilma yoki foydalanuvchi tavsifi (masalan: Ruslan Laptop)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ruxsat etilgan IP',
                'verbose_name_plural': 'Ruxsat etilgan IPlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
