# Generated by Django 5.1.5 on 2026-03-09 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordChangeOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('new_password_hash', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_otp_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parol OTP',
                'verbose_name_plural': 'Parol OTPlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_used'], name='otp_user_used_idx')],
            },
        ),
    ]
