# Generated by Django 5.1.5 on 2026-03-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_password_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_volunteer',
            field=models.BooleanField(default=False, help_text='Volunteer team member'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, help_text="User's home region", max_length=100, null=True),
        ),
    ]
