# Generated by Django 5.1.5 on 2026-01-27 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='Correct answer for automatic scoring', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Direct video file upload', null=True, upload_to='lesson_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg'])]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube unlisted link or embedded video URL', null=True),
        ),
    ]
