# Generated by Django 5.1.5 on 2026-01-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_assignment_correct_answer_lesson_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='points_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
