# Generated by Django 5.1.5 on 2026-01-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_submission_points_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='resource_file',
            field=models.FileField(blank=True, help_text='Additional lesson resources (PDF, DOCX, etc.)', null=True, upload_to='lesson_resources/'),
        ),
    ]
