# Generated by Django 5.1.5 on 2026-01-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_resource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Upload a certificate for this student', null=True, upload_to='certificates/'),
        ),
    ]
