# Generated by Django 5.1.5 on 2026-02-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_submission_certificate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='option_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='option_b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='option_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='option_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='allow_file_upload',
            field=models.BooleanField(default=False, help_text='Allow students to upload files'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='correct_answer',
            field=models.CharField(blank=True, help_text="Correct answer (e.g., 'A', 'B', 'C', or 'D')", max_length=255, null=True),
        ),
    ]
