# Generated by Django 5.1.5 on 2026-02-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_assignment_option_a_assignment_option_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
