# Generated by Django 5.1.5 on 2026-02-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_comment_options_comment_disliked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='last_watched_time',
            field=models.FloatField(default=0.0, help_text='Seconds watched'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='progress',
            field=models.FloatField(default=0.0, help_text='Percentage 0-100'),
        ),
    ]
