# Generated by Django 5.1.5 on 2026-02-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_lesson_saved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='points_tier',
            field=models.IntegerField(default=0, help_text='0: none, 1: 20pts, 2: 40pts, 3: 60pts'),
        ),
    ]
