# Generated by Django 5.1.5 on 2026-02-13 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_enrollment_points_tier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='quiz_passed',
            field=models.BooleanField(default=False, help_text='Whether user passed the lesson quiz'),
        ),
        migrations.CreateModel(
            name='LessonQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Savol matni')),
                ('option_a', models.CharField(help_text='A variant', max_length=500)),
                ('option_b', models.CharField(help_text='B variant', max_length=500)),
                ('option_c', models.CharField(blank=True, help_text='C variant (ixtiyoriy)', max_length=500, null=True)),
                ('option_d', models.CharField(blank=True, help_text='D variant (ixtiyoriy)', max_length=500, null=True)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text="To'g'ri javob (A, B, C yoki D)", max_length=1)),
                ('order', models.PositiveIntegerField(default=0, help_text='Savol tartibi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Lesson Quiz Question',
                'verbose_name_plural': 'Lesson Quiz Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict, help_text="User answers: {question_id: 'A'/'B'/'C'/'D'}")),
                ('score', models.IntegerField(default=0, help_text='Number of correct answers')),
                ('total_questions', models.IntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
    ]
