# Generated by Django 5.1.5 on 2026-02-14 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_enrollment_quiz_passed_lessonquiz_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='test_file',
            field=models.FileField(blank=True, help_text="Test fayli (PDF yoki DOCX formatida). Test savollarini qo'shmasangiz, bu majburiy.", null=True, upload_to='lesson_tests/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc'])]),
        ),
    ]
