# Generated by Django 5.1.5 on 2026-03-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_add_test_file_to_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='hls_playlist',
            field=models.CharField(blank=True, help_text="HLS master.m3u8 fayl yo'li (media/ dan)", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='hls_status',
            field=models.CharField(choices=[('none', "HLS yo'q"), ('processing', 'Konvertatsiya jarayonida'), ('ready', 'Tayyor'), ('error', 'Xatolik')], default='none', help_text='HLS konvertatsiya holati', max_length=20),
        ),
    ]
