# Generated by Django 5.1.5 on 2026-03-09 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_add_hls_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['lesson', 'parent'], name='comment_lesson_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'lesson'], name='enrollment_user_lesson_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user'], name='enrollment_user_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['sub_category'], name='lesson_subcategory_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['author'], name='lesson_author_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['level'], name='lesson_level_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['-views'], name='lesson_views_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['-likes'], name='lesson_likes_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['is_published', '-created_at'], name='lesson_published_created_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonlike',
            index=models.Index(fields=['user', 'lesson'], name='lessonlike_user_lesson_idx'),
        ),
    ]
