# Generated by Django 5.1.5 on 2026-03-23 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_optimize_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sub-Sub-Category',
                'verbose_name_plural': 'Sub-Sub-Categories',
                'ordering': ['sub_category', 'name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='lesson_subcategory_idx',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_subcategories', to='courses.subcategory'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='sub_sub_category',
            field=models.ForeignKey(blank=True, help_text="Dars tegishli bo'lgan sub-subkategoriya", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.subsubcategory'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['sub_sub_category'], name='lesson_subsubcategory_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subsubcategory',
            unique_together={('sub_category', 'name')},
        ),
    ]
